site_name: C.G.T
site_url: http://chainreactionist.com/C.G.T/
repo_name: Chainreactionist/C.G.T
repo_url: https://github.com/Chainreactionist/C.G.T

theme:
  icon:
    logo: material/star
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  palette:
    primary: "light blue"
    accent: "light blue"
    scheme: slate
  features:
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Code Template: template.md
  - Services:
      - PlayerDataService: Services/PlayerDataService.md
      - PlayerTempDataService: Services/PlayerTempDataService.md
      - CommandBarService: Services/CommandBarService.md
  - Controllers:
      - CommandBarController: Controllers/CommandBarController.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
