[package]
name = "evaera/cmdr"
description = "Extensible command console for Roblox developers"
version = "1.8.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
